name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: publish
      run: dotnet publish src/SharerBlazorServer -r win-x64 --no-self-contained
    - name: Upload SharerBlazorServer Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SharerBlazorServer
        path: src/SharerBlazorServer/bin/Debug/netcoreapp3.1/win-x64/publish/
